# fly.toml app configuration file generated for habits-tfjjnq on 2025-06-29T19:20:35Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'habits-tfjjnq'
primary_region = 'gig'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
